# Basic Information 
title: Guhan Zheng
position: Associate Professor
department: School of Communication and Information Engineering (SCIE)
department_link: https://scie-en.shu.edu.cn/
affiliation: Shanghai University
affiliation_link: https://en.shu.edu.cn/
affiliation_logo: ./assets/img/图片1.png
email: gzheng@shu.edu.cn

# Search Engine Optimization (SEO)
keywords: Guhan Zheng, 郑谷寒
canonical: https://scie.shu.edu.cn/
description: Guhan Zheng is an Associate Professor at Shanghai University. 

# The option is used to enable the Johns Hopkins template.
enable_hopkins_logo: false

# The option is used to show the last update time.
enable_last_update: true

# Links
link_type: icon #text/icon
google_scholar: https://scholar.google.com/citations?user=377WJ7IAAAAJ&hl
linkedin: https://www.linkedin.com/in/guhan-zheng-69139a184/
orcid: https://orcid.org/0000-0001-5602-1108

# Images 
avatar: ./assets/img/2寸照.jpg 
favicon: ./assets/img/pic1.ico
favicon_dark: ./assets/img/pic1.ico

# The following files will be removed from the generated website.
exclude:
  - build.sh
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - CNAME
